# Generated by Django 2.2 on 2020-02-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAuthorsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='old book table'),
            preserve_default=False,
        ),
    ]
