# Generated by Django 2.2 on 2020-02-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksAuthorsApp', '0002_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='BooksAuthorsApp.Book'),
        ),
    ]
